### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Sudhee-bsp** [ruvictor/login-with-google#1]
Like after Logging with Google, still its redirecting to index.php# and homescreen remains same.

**Comment by Suyumbekov** [comment]
> Like after Logging with Google, still its redirecting to index.php# and homescreen remains same.

in the file "controller.php"
on the 11th line:
if(isset($token["error"]) && ($token["error"] != "invalid_grant")){
change to
if(!isset($token["error"]) && ($token["error"] != "invalid_grant")){

**Comment by Sudhee-bsp** [comment]
Great! Then I'll close this issue.
